//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticCodeAnalysisWebService.PMDToolWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PMDToolWebService.IPMDToolService")]
    public interface IPMDToolService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMDToolService/RunPMDTool", ReplyAction="http://tempuri.org/IPMDToolService/RunPMDToolResponse")]
        string RunPMDTool();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMDToolService/RunPMDTool", ReplyAction="http://tempuri.org/IPMDToolService/RunPMDToolResponse")]
        System.Threading.Tasks.Task<string> RunPMDToolAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPMDToolServiceChannel : StaticCodeAnalysisWebService.PMDToolWebService.IPMDToolService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PMDToolServiceClient : System.ServiceModel.ClientBase<StaticCodeAnalysisWebService.PMDToolWebService.IPMDToolService>, StaticCodeAnalysisWebService.PMDToolWebService.IPMDToolService {
        
        public PMDToolServiceClient() {
        }
        
        public PMDToolServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PMDToolServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMDToolServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMDToolServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RunPMDTool() {
            return base.Channel.RunPMDTool();
        }
        
        public System.Threading.Tasks.Task<string> RunPMDToolAsync() {
            return base.Channel.RunPMDToolAsync();
        }
    }
}
